### ISSUE TITLE
Is this library intended to be used only within nodejs?

### ISSUE THREAD

**Issue by aaalrightalrightalright** [sindresorhus/fnv1a#11]
Hi @sindresorhus, this is more of a question for understanding than an issue.

I've encountered at least one other OSS project, https://github.com/nearform/graphql-hooks (specifically, the https://github.com/nearform/graphql-hooks/tree/master/packages/graphql-hooks-memcache package), that is using your `v2.0.0` of your package, but within both `nodejs` AND browser. This got me thinking towards the intent of this library - is it intended to be used only within `nodejs`?

If so, then that means maintainers of other projects aren't using your package correctly then, and this may cause/allow them to then do so. Would first like to gain this understanding though.

**Comment by aaalrightalrightalright** [comment]
Thinking more now after my post, I think that the library is geared in general towards any environment that **does** currently support BigInt... would that be a more proper conclusion then?

**Comment by sindresorhus** [comment]
> I think that the library is geared in general towards any environment that does currently support BigInt... would that be a more proper conclusion then?

Correct
