### ISSUE TITLE
About Unicode

### ISSUE THREAD

**Issue by cadl** [sindresorhus/fnv1a#2]
The '🦄🌈'.charCodeAt(0) is 55358. It out of the byte range.

https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function#FNV-1a_hash
```
   hash = FNV_offset_basis
   for each byte_of_data to be hashed
   	hash = hash XOR byte_of_data
   	hash = hash × FNV_prime
   return hash
```

**Comment by sindresorhus** [comment]
Not clear exactly what the problem is. Can you elaborate or submit a failing test?

**Comment by cadl** [comment]
> fnv1a('🦄🌈');
> //=> 582881315 = 0x22be1023


---------

http://www.nitrxgen.net/hashgen/
![image](https://user-images.githubusercontent.com/1629582/50888932-affc2080-1431-11e9-89b7-6536a8956886.png)

--------

https://www.tools4noobs.com/online_tools/hash/
![image](https://user-images.githubusercontent.com/1629582/50889039-edf94480-1431-11e9-9847-03807a07c95e.png)
